name: Deploy to Google Cloud (UAT)

on:
  pull_request:
    branches:
      - uat

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List current directory
        run: ls -la

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCLOUD_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.GCLOUD_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync over SSH
        run: |
          rsync -avz --no-times --delete \
            --exclude='.github' \
            --exclude='.git' \
            --exclude='.gitignore' \
            --exclude='composer.json' \
            --exclude='package.json' \
            --exclude='bs-config.js' \
            -e "ssh -o StrictHostKeyChecking=no" \
            "${{ github.workspace }}/" \
            "${{ secrets.GCLOUD_USER }}@${{ secrets.GCLOUD_HOST }}:/var/www/swisscontact-fuentesmoviles/"
